-- 실습8-4. 조인의 가장 기본 형태
SELECT 
    E.EMPNO
, E.ENAME
, E.DEPTNO
, D.DNAME
, D.LOC 
FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO;

SELECT * 
FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO;

SELECT E.ENAME, D.*
FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO
AND D.LOC = 'CHICAGO';

-- 210페이지. 1분복습
SELECT E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME, D.LOC 
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO 
AND E.SAL >= 2500
AND E.EMPNO <= 9999;
ORDER BY E.EMPNO;


-- 실습8-7. 비등가조인 (잘 안씀)
-- 급여 범위를 지정하는 조건식으로 조인하기
SELECT *
FROM EMP E, SALGRADE S 
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT *
FROM EMP E, SALGRADE S 
WHERE E.SAL <= S.HISAL
ORDER BY EMPNO 
;
-- 자체조인(셀프조인)
SELECT 
E1.EMPNO, E1.ENAME, E1.MGR, 
E2.ENAME
FROM EMP E1, EMP E2 
WHERE E1.MGR = E2.EMPNO ;

-- 지금까지는 이너조인

-- 외부조인(LEFT아우터조인-문법은 오른쪽에+붙여줌.)
SELECT 
     E1.EMPNO 
     ,E1.ENAME 
     ,E1.MGR
     ,E2.ENAME 
    FROM EMP E1, EMP E2 
    WHERE E1.MGR = E2.EMPNO(+);

-- 외부조인(RIGHT아우터조인-문법은 왼쪽에+붙여줌.)
SELECT 
     E1.EMPNO 
     ,E1.ENAME 
     ,E1.MGR
     ,E2.EMPNO
     ,E2.ENAME 
    FROM EMP E1, EMP E2 
    WHERE E1.MGR(+) = E2.EMPNO;

SELECT 
     E.EMPNO 
     ,E.ENAME
     ,E.DEPTNO 
     ,D.DEPTNO AS DNO  
     ,D.DNAME
     FROM EMP E, DEPT_TEMP D 
    WHERE E.DEPTNO(+) = D.DEPTNO;


-- 실습8-8. 같은 테이블 두 번 사용하여 자체 조인하기
SELECT 
    E1.EMPNO
    , E1.ENAME
    , E1.MGR 
    , E2.EMPNO AS MGR_EMPNO
    , E2.ENAME AS MGR_ENAME 
    FROM EMP E1, EMP E2 
    WHERE E1.MGR = E2.EMPNO;

-- 실습8-9. 왼쪽 외부 조인 사용하기
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
    E2.EMPNO AS MGR_EMPNO,
    E2.ENAME AS MGR_ENAME 
    FROM EMP E1, EMP E2 
    WHERE E1.MGR = E2.EMPNO(+)
    ORDER BY E1.EMPNO;

-- 실습8-10. 오른쪽 외부 조인 사용하기
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
    E2.EMPNO AS MGR_EMPNO,
    E2. ENAME AS MGR_ENAME 
    FROM EMP E1, EMP E2
    WHERE E1.MGR(+) = E2.EMPNO
    ORDER BY E1.EMPNO;


-- 등가조인을 JOIN~ON으로 바꾸기.
SELECT 
    E.EMPNO
    ,E.ENAME
    ,E.DEPTNO
    ,D.DEPTNO 
    ,D.DNAME
    ,D.LOC
    -- FROM EMP E, DEPT D, SALGRADE S 
    FROM EMP E 
    JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
    -- WHERE E.DEPTNO = D.DEPTNO
    WHERE E.EMPNO = 7788
    ;

-- 비등가조인을 바꾸기
SELECT * 
FROM EMP E
JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
-- WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY EMPNO
;

-- 자체조인을 바꾸기
SELECT 
    E1.EMPNO
    , E1.ENAME
    , E1.MGR 
    , E2.EMPNO AS MGR_EMPNO
    , E2.ENAME AS MGR_ENAME 
    FROM EMP E1
    JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    -- WHERE E1.MGR = E2.EMPNO
    ;


SELECT 
    E1.EMPNO
    , E1.ENAME
    , E1.MGR 
    , E2.EMPNO
    , E2.MGR 
    FROM EMP E1
    LEFT OUTER JOIN EMP E2 ON (E2.EMPNO = E1.MGR)
    -- RIGHT OUTER JOIN EMP E2 ON (E2.EMPNO = E1.MGR)
    ;

-- 바꾸기 전 (8-9. 왼쪽 외부 조인)
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
    E2.EMPNO AS MGR_EMPNO,
    E2.ENAME AS MGR_ENAME 
    FROM EMP E1, EMP E2 
    WHERE E1.MGR = E2.EMPNO(+)
    ORDER BY E1.EMPNO;

-- 바꾸기 후 
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
    E2.EMPNO AS MGR_EMPNO,
    E2.ENAME AS MGR_ENAME 
    FROM EMP E1
    LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY E1.EMPNO;

-- 바꾸기 전 (8-10. 오른쪽 외부 조인)
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
    E2.EMPNO AS MGR_EMPNO,
    E2. ENAME AS MGR_ENAME 
    FROM EMP E1, EMP E2
    WHERE E1.MGR(+) = E2.EMPNO
    ORDER BY E1.EMPNO;

-- 바꾸기 후
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
    E2.EMPNO AS MGR_EMPNO,
    E2.ENAME AS MGR_ENAME 
    FROM EMP E1
    RIGHT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY E1.EMPNO;

-- 테이블 생성
CREATE TABLE SALGRADE_TEM 
    AS SELECT * FROM SALGRADE;

CREATE TABLE EMP_TEM
    AS SELECT * FROM EMP;    
    
-- 조인
SELECT * FROM EMP_TEM E, SALGRADE_TEM S
    WHERE E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
    ;

SELECT * 
FROM EMP_TEM E, SALGRADE_TEM S
WHERE E.SAL(+) BETWEEN S.LOSAL AND S.HISAL
ORDER BY EMPNO
;


-- 조인으로 바꾼 버전
SELECT *
FROM EMP_TEMP E
LEFT JOIN SALGRADE_TEM S
    ON E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY E.EMPNO;

-- 225페이지. 1분복습
-- 
SELECT 
E.EMPNO , E.ENAME , E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM 
, DEPTNO
, D.DNAME, D.LOC
FROM EMP E 

JOIN DEPT D USING (DEPTNO)
WHERE E.MGR IS NOT NULL
AND E.SAL >= 3000

ORDER BY DEPTNO, E.EMPNO;



-- 전체외부조인(풀아우터조인)은 존재하지 않음.
-- 유니온집합연산자를 활용해야함

