-- 실습9-3. 
SELECT *
from emp 
WHERE sal > (SELECT sal from emp 
where ename = 'JONES');

-- 실습9-4. 
SELECT *
from emp 
WHERE hiredate < (select hiredate from emp
WHERE ename = 'SCOTT');

-- 실습9-18. 
SELECT * FROM EMP 
WHERE (DEPTNO, SAL) 
    IN (SELECT DEPTNO, MAX(SAL) 
    FROM EMP 
    GROUP BY DEPTNO);

-- 실습9-19. 
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO
    , D.DNAME, D.LOC
FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E10 ,
     (SELECT * FROM DEPT) D 
WHERE E10.DEPTNO = D.DEPTNO;

-- 실습9-20.
WITH 
E10 AS (SELECT *FROM EMP WHERE DEPTNO = 10),
D AS (SELECT *FROM DEPT)
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC 
FROM E10, D 
WHERE E10.DEPTNO = D.DEPTNO;

-- 실습9-21. 
SELECT EMPNO, ENAME, JOB, SAL,
    (SELECT GRADE 
    FROM SALGRADE
    WHERE E.SAL BETWEEN LOSAL AND HISAL) AS SALGRADE,
    DEPTNO,
    (SELECT DNAME
    FROM DEPT
    WHERE E.DEPTNO = DEPT.DEPTNO) AS DNAME
FROM EMP E; 


-- 9장. 되새김문제
-- 1. 
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL,
       D.DEPTNO, D.DNAME
      FROM EMP E

JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.JOB = 
    (SELECT JOB 
    FROM EMP
    WHERE ENAME = 'ALLEN')
;

-- 2. 
SELECT E.EMPNO, E.ENAME
, D.DNAME, TO_CHAR(E.HIREDATE,'YY/MM/DD') HIREDATE
, D.LOC
, E.SAL
, S.GRADE
FROM EMP E 
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
JOIN SALGRADE S 
ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE E.SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY D.DEPTNO ;


-- 3. 
SELECT JOB, DEPTNO FROM EMP

ORDER BY DEPTNO;
