CREATE table dept_temp
    as SELECT * from dept;

-- 실습10-3
INSERT into dept_temp (deptno, dname, loc)
values (50, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_TEMP;

-- 
INSERT into dept_temp (deptno, dname, loc)
values (60   , 'NETWORK'    );
    --> 지정한 열보다 입력할 데이터 개수가 적어서 생긴 오류
-- 
INSERT into dept_temp (deptno, dname, loc)
values ('WRONG', 'NETWORK', 'BUSAN', 'WRONG');   
    --> 지정한 열보다 데이터 개수가 많아서 생긴 오류
-- 
INSERT into dept_temp (deptno, dname, loc)
values ('WRONG', 'NETWORK', 'BUSAN'); 
    --> 숫자데이터가 들어가야 할 열에 문자열데이터를 지정하여 생긴 오류
-- 
INSERT into dept_temp (deptno, dname, loc)
values (600, 'NETWORK', 'BUSAN'); 
     -->두자리수까지 허용되는 부서번호 열에 세자리수를 넣어 생긴 오류


-- 실습10-5
-- 널 지정하여 입력하기
INSERT into dept_temp (deptno, dname, loc)
    values (70, 'WEB', NULL);

-- 10.6 
-- 빈 공백 문자열로 널 입력
INSERT into dept_temp (deptno, dname, loc)
    values (80, 'MOBILE', '');

SELECT * FROM DEPT_TEMP;

-- 10-7 
-- 열 데이터 넣지 않고 널 입력
INSERT into dept_temp (deptno, loc)
    values (90, 'INCHEON');

SELECT * FROM DEPT_TEMP;

-- 10-8 
CREATE TABLE EMP_TEMP
AS SELECT *
FROM EMP 
WHERE 1 <> 1;

SELECT * FROM EMP_TEMP;

-- 10-12 
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR,
    HIREDATE, SAL, COMM, DEPTNO)
        VALUES (2111, '이순신', 'MANAGER', 9999,
            TO_DATE('08/07/2026', 'DD/MM/YYYY'),
            4000, NULL, 20);

SELECT * FROM EMP_TEMP;

-- 10-13 
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR,
    HIREDATE, SAL, COMM, DEPTNO)
        VALUES (3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000,
        NULL, 30);

SELECT * FROM EMP_TEMP;

-- 10-14 
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR,
    HIREDATE, SAL, COMM, DEPTNO)
    SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
    FROM EMP E, SALGRADE S 
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL 
    AND S.GRADE = 1;

SELECT * FROM EMP_TEMP;

-- 10-15 
CREATE TABLE DEPT_TEMP2
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2;

-- 10-16 
UPDATE DEPT_TEMP2
SET LOC = 'SEOUL';

SELECT * FROM DEPT_TEMP2;
--> 기존값: 뉴욕, 댈러스, 시카고, 보스턴
--> 변경후: LOC열 모두 서울로 변경됨 (WHERE절의 조건이 없기 때문)

ROLLBACK;
-- 되돌리기(커밋 전에 가능)
-- COMMIT; (저장)


SELECT * FROM DEPT_TEMP2;

-- 10-18 
UPDATE DEPT_TEMP2
SET DNAME = 'DATABASE', --열이름=수정할값(문자열),열이름=수정할값(문자열)...
    LOC = 'SEOUL'
WHERE DEPTNO = 40;

-- 1분복습
UPDATE EMP_TEMP
SET COMM = 50
WHERE SAL <= 2500;

SELECT * FROM EMP_TEMP;

-- 10-21 
UPDATE DEPT_TEMP2
SET LOC = 'SEOUL'
WHERE DEPTNO = (SELECT DEPTNO 
                FROM DEPT_TEMP2
                WHERE DNAME = 'OPERATION');

SELECT * FROM DEPT_TEMP2;

-- 10-22 
CREATE TABLE EMP_TEMP2
AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP2;

-- 10-23
DELETE FROM EMP_TEMP2
WHERE JOB = 'MANAGER';

SELECT * FROM EMP_TEMP2;

-- 1분복습
DELETE FROM EMP_TEMP2
WHERE SAL >= 3000;
SELECT * FROM EMP_TEMP2;

-- 되새김문제
CREATE TABLE CHAP10HW_EMP AS SELECT * FROM EMP;
CREATE TABLE CHAP10HW_DEPT AS SELECT * FROM DEPT;
CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE;

-- 1. 
INSERT INTO CHAP10HW_DEPT(DEPTNO, DNAME, LOC)
VALUES (50, 'ORACLE', 'BUSAN');
INSERT INTO CHAP10HW_DEPT(DEPTNO, DNAME, LOC)
VALUES (60, 'SQL', 'ILSAN');
INSERT INTO CHAP10HW_DEPT(DEPTNO, DNAME, LOC)
VALUES (70, 'SELECT', 'INCHON');
INSERT INTO CHAP10HW_DEPT(DEPTNO, DNAME, LOC)
VALUES (80, 'DML', 'BUNDANG');

SELECT * FROM CHAP10HW_DEPT;

-- 2. 
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7201, 'TEST_USER1', 'MANAGER', 7788, TO_DATE('16/01/02','YY/MM/DD'), 4500, NULL, 50);
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7202, 'TEST_USER2', 'CLERK', 7201, TO_DATE('16/02/21','YY/MM/DD'), 1800, NULL, 50);
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7203, 'TEST_USER3', 'ANALIST', 7201, TO_DATE('16/04/11','YY/MM/DD'), 3400, NULL, 60);
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7204, 'TEST_USER4', 'SALESMAN', 7201, TO_DATE('16/05/31','YY/MM/DD'), 2700, 300, 60);
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7205, 'TEST_USER5', 'CLERK', 7201, TO_DATE('16/07/20','YY/MM/DD'), 2600, NULL, 70);
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7206, 'TEST_USER6', 'CLERK', 7201, TO_DATE('16/09/08','YY/MM/DD'), 2600, NULL, 70);
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7207, 'TEST_USER7', 'LECTURER', 7201, TO_DATE('16/10/28','YY/MM/DD'), 2300, NULL, 80);
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7208, 'TEST_USER8', 'STUDENT', 7201, TO_DATE('18/03/09','YY/MM/DD'), 1200, NULL, 80);

SELECT * FROM CHAP10HW_EMP;

-- 3. 
SELECT * FROM CHAP10HW_EMP;
-- 오류
UPDATE CHAP10HW_EMP
SET DEPTNO = 70
WHERE DEPTNO = 50 
AND SAL > AVG(SAL) (SELECT AVG(SAL)     --★WHERE절에서 집계함수 사용 불가 
                    FROM EMP
                    WHERE DEPTNO = 50)
;
-- 수정
UPDATE CHAP10HW_EMP
SET DEPTNO = 70
WHERE DEPTNO = 50 
AND SAL > (SELECT AVG(SAL)             
            FROM CHAP10HW_EMP           
            WHERE DEPTNO = 50);         

-- 4.
UPDATE CHAP10HW_EMP
SET DEPTNO = 80, SAL = SAL*1.1
WHERE HIREDATE > (SELECT MIN(HIREDATE)
                 FROM CHAP10HW_EMP
                 WHERE DEPTNO = 60);

SELECT * FROM CHAP10HW_EMP;

-- 5. CHAP10HW_SALGRADE
DELETE FROM CHAP10HW_EMP
WHERE EMPNO = IN ( 
    SELECT E.EMPNO
    FROM CHAP10HW_EMP E, CHAP10HW_SALGRADE S 
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND S.GRADE = 5);
    
SELECT EMPNO, ENAME, JOB, MGR, TO_CHAR(HIREDATE, 'YY/MM/DD') HIREDATE, SAL, COMM, DEPTNO
 FROM CHAP10HW_EMP;







select * from dept_temp;

DELETE from dept_temp where deptno = 10;

commit;

UPDATE dept_temp
set loc = 'busan1'
where deptno = 30;

select * from dept_temp;



-- 11장 되새김문제
CREATE table dept_hw
    as SELECT * from dept;

select * from dept_hw;

UPDATE dept_hw
set dname = 'DATABASE', LOC='SEOUL'
WHERE DEPTNO = 30;

ROLLBACK;

SELECT * FROM DEPT_HW; --원복

-- 11장 되새김문제 A
UPDATE dept_hw
set dname = 'DATABASE', LOC='BUSAN'
WHERE DEPTNO = 30;

select * from dept_hw;



ROLLBACK;

SELECT * FROM DEPT_HW; --원복


-- 
-- 12.1
CREATE TABLE EMP_DDL( 
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB   VARCHAR2(9),
    MGR   NUMBER(4),
    HIREDATE DATE,
    SAL   NUMBER(7,2),
    COMM  NUMBER(7,2),
    DEPTNO NUMBER(2)
);

DESC EMP_DDL;

-- 12-6
CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
    ADD HP VARCHAR2(20);

SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
    RENAME COLUMN HP TO TEL;

ALTER TABLE EMP_ALTER
    MODIFY EMPNO NUMBER(5);

DESC EMP_ALTER;

ALTER TABLE EMP_ALTER
DROP COLUMN TEL;

-- 12장 되새김문제 (인서트하지말기)
-- 1
CREATE TABLE EMP_HW(
    EMPNO   NUMBER(4),
    ENAME   VARCHAR2(10),
    JOB     VARCHAR2(9),
    MGR     NUMBER(4),
    HIREDATE DATE,
    SAL     NUMBER(7,2),
    COMM    NUMBER(7,2),
    DEPTNO  NUMBER(2)
);
-- 2
ALTER TABLE EMP_HW
ADD BIGO VARCHAR2(20)
;



-- 13장

CREATE TABLE TABLE_NOTNULL( 
        LOGIN_ID VARCHAR2(20) NOT NULL,
        LOGIN_PW VARCHAR2(20) NOT NULL,
        TELL VARCHAR2(20)
);

DESC TABLE_NOTNULL;

INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PW, TEL)
VALUES ('TEST_ID_01', NULL, '010-1234-5678');


ALTER TABLE TABLE_NOTNULL
MODIFY(TEL NOT NULL);
-- 
CREATE TABLE TABLE_UNIQUE( 
        LOGIN_ID VARCHAR2(20) UNIQUE,
        LOGIN_PW VARCHAR2(20) NOT NULL,
        TEL VARCHAR2(20)
);

DESC TABLE_UNIQUE;

ALTER TABLE TABLE_UNIQUE
    RENAME COLUMN TELL TO TEL;


-- 
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PW, TEL)
VALUES('TEST_ID_01', 'PWD01', '010-1234-5678');
SELECT * FROM TABLE_UNIQUE;
COMMIT;
--컬럼명수정,커밋,확인

INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PW, TEL)
VALUES('TEST_ID_01', 'PWD01', '010-1234-5678');
-- 중복되는데이터라 안됨

-- 
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PW, TEL)
VALUES(NULL, 'PWD01', '010-1234-5678');
SELECT * FROM TABLE_UNIQUE;

UPDATE TABLE_UNIQUE
SET LOGIN_ID = 'TEST_ID_01'
WHERE LOGIN_ID IS NULL;
--무결성 제약조건에 위배

ALTER TABLE TABLE_UNIQUE
MODIFY(TEL UNIQUE);
-- TEL에 이미 중복값 입력돼서 수정 안됨


ALTER TABLE "SCOTT"."EMP_TEMP" ADD CONSTRAINT PK_EMP_TEMP PRIMARY KEY(EMPNO);


-- 14-29
CREATE TABLE TABLE_PK( 
        LOGIN_ID VARCHAR2(20) PRIMARY KEY,
        LOGIN_PW VARCHAR2(20) NOT NULL,
        TEL VARCHAR2(20)
);

DESC TABLE_UNIQUE;

-- 14-39~44
CREATE TABLE DEPT_FK (
DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
ENAME VARCHAR2(14),
LOC VARCHAR2(13)
);
DESC DEPT_FK;

-- 
CREATE TABLE EMP_FK (
EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK (DEPTNO)
);

DESC EMP_FK;

-- 
INSERT INTO EMP_FK 
VALUES(9999, 'TEST_NAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01','YYYY/MM/DD'),
3000,NULL,10);
-- 부서번호 데이터가 아직 부서정보(외래키)테이블에 없어서 에러발생

-- 
INSERT INTO DEPT_FK 
VALUES(10, 'TEST_DNAME','TEST_LOC');
SELECT * FROM DEPT_FK;

-- 
INSERT INTO EMP_FK
VALUES(9999, 'TEST_NAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01','YYYY/MM/DD'),
3000,NULL,10);
SELECT * FROM EMP_FK;

DELETE FROM DEPT_FK
WHERE DEPTNO = 10;
-- 무결성 제약조건으로 오류 발생

-- 14-45
CREATE TABLE TABLE_CHECK( 
        LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY,
        LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLCK_LOGINPW_CK CHECK (LENGTH(LOGIN_PWD)>3),
        TEL VARCHAR2(20)
);

DESC TABLE_CHECK;

-- 14-46
INSERT INTO TABLE_CHECK 
VALUES ('TEST_ID', '123', '010-1234-5678');

-- 오라클테이블정의서쿼리

-- 14장 되새김문제
-- 1
CREATE TABLE DEPT_CONST(
    DEPTNO NUMBER(2) CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY,
    DNAME VARCHAR2(14) CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE,
    LOC VARCHAR2(13) CONSTRAINT DEPTCONST_LOC_NN NOT NULL
);

DESC DEPT_CONST;

-- 2






CREATE TABLE EMP_CONST(
    EMPNO NUMBER(4) CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10) CONSTRAINT EMPCONST_ENAME_NN NOT NULL,
    JOB VARCHAR2(9) ,
    TEL VARCHAR2(20) CONSTRAINT EMPCONST_TEL_UNQ UNIQUE,
    HIREDATE DATE,
    SAL NUMBER(7,2) CONSTRAINT EMPCONST_SAL_CHK CHECK (SAL BETWEEN 1000 AND 9999),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2) CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES EMP_CONST(DEPTNO)
);

